source ~/.config/nvim/init/plugin_polyglot.vim
source ~/.config/nvim/init/plugin_ale.vim
source ~/.config/nvim/init/plugged.vim
source ~/.config/nvim/init/options.vim
source ~/.config/nvim/init/theme.vim
source ~/.config/nvim/init/plugin_syntastic.vim
source ~/.config/nvim/init/plugin_nerdtree.vim
source ~/.config/nvim/init/plugin_nerdtree-tabs.vim
source ~/.config/nvim/init/plugin_nerdtree-syntax-highlight.vim
source ~/.config/nvim/init/plugin_deoplete.vim
source ~/.config/nvim/init/plugin_tagbar.vim
source ~/.config/nvim/init/plugin_split-term.vim
source ~/.config/nvim/init/plugin_ctrlsf.vim
source ~/.config/nvim/init/plugin_ctrlp.vim
source ~/.config/nvim/init/plugin_better-whitespace.vim
source ~/.config/nvim/init/plugin_neosnippet.vim
source ~/.config/nvim/init/plugin_typescript.vim
"source ~/.config/nvim/init/plugin_tsuquyomi.vim
source ~/.config/nvim/init/plugin_devicons.vim
source ~/.config/nvim/init/plugin_airline.vim
source ~/.config/nvim/init/plugin_eighties.vim
source ~/.config/nvim/init/plugin_table-mode.vim
source ~/.config/nvim/init/plugin_gina.vim
source ~/.config/nvim/init/plugin_indent-guides.vim
source ~/.config/nvim/init/plugin_php_cs_fixer.vim
source ~/.config/nvim/init/plugin_phpactor.vim
source ~/.config/nvim/init/plugin_ncm2.vim
source ~/.config/nvim/init/plugin_go.vim
source ~/.config/nvim/init/plugin_coc.vim
source ~/.config/nvim/init/plugin_quickui.vim
source ~/.config/nvim/init/plugin_phpstan.vim
source ~/.config/nvim/init/plugin_qfenter.vim
source ~/.config/nvim/init/plugin_prettier.vim
source ~/.config/nvim/init/shortcuts.vim
